server:
  port: 8989
spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
zuul:
  routes:
    movie-rating-service:
      path: /movierating/**
      serviceId: movie-rating-service
      stripPrefix: false
    movie-service:
      path: /movies/**
      serviceId: movie-service
      stripPrefix: false
logging:
  level:
    org:
      keycloak: trace
      springframework.security: debug