server:
  port: 8091
#  ssl:
#    enabled: true
#    key-alias: movie-service
#    key-password: temp123
#    key-store-password: temp123
#    key-store-type: jks
#    key-store: classpath:awsdemo-keystore.jks
spring:
  application:
    name: movie-service



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}
  instance:
    preferIpAddress: true